<!-- products_table_row2.inc BEGIN -->
<tr>
	<td class="preview2"><img src="${image}" /></td>
	<td>
		<!--
		<ul>
			<li>Изготовитель: ${fabricName}</li>
			<li>Страна: ${fabricCountry}</li>
			<li>Тип: ${type}</li>
			<li>Формат: ${format}</li>
			<li>Разрешение: ${resolution}</li>
			<li>Модель: ${model}</li>
			<li>Диагональ: ${diagonal}</li>
			<li>Цена: ${price}</li>
		</ul>
		-->
	</td>
</tr>
<!-- products_table_row2.inc END -->
