<!-- products_table_row.inc BEGIN -->
<tr>
	<td class="preview"><img src="${image}" /></td>
	<td>
		<ul>
			<li>Изготовитель: ${fabricName}</li>
            <li>Страна: ${fabricCountry}</li>
            <li>Тип: ${type}</li>
            <li>Формат: ${format}</li>
            <li>Разрешение: ${resolution}</li>
            <li>Модель: ${model}</li>
            <li>Диагональ: ${diagonal}</li>
            <li>Цена: ${price}</li>
		</ul>
	</td>
</tr>
<!-- products_table_row.inc END -->
